export const PROXY_CONFIG = {
  baseUrl:
    import.meta.env.VITE_PROXY_BASE_URL ??
    "https://proxy-server.jameswilliamstrutt.workers.dev",
  allowedDomains: [
    "api.apps1.nsw.gov.au",
    "api.metromap.com.au",
    "api.transport.nsw.gov.au",
    "arcgis.paggis.nsw.gov.au",
    "en.wikipedia.org",
    "layers-node-ehcce5pxxq-ts.a.run.app",
    "maps.google.com",
    "maps.googleapis.com",
    "maps.six.nsw.gov.au",
    "mapprod.environment.nsw.gov.au",
    "mapprod1.environment.nsw.gov.au",
    "mapprod2.environment.nsw.gov.au",
    "mapprod3.environment.nsw.gov.au",
    "mapuat3.environment.nsw.gov.au",
    "mapservices.randwick.nsw.gov.au",
    "portal.data.nsw.gov.au",
    "portal.spatial.nsw.gov.au",
    "services-ap1.arcgis.com",
    "services.arcgis.com",
    "services9.arcgis.com",
    "services.ga.gov.au",
    "sims.spatial.nsw.gov.au",
    "spatial.industry.nsw.gov.au",
    "spatialportalarcgis.dpie.nsw.gov.au",
    "transportnsw.info",
    "www.getsoldprice.com.au",
    "www.lmbc.nsw.gov.au",
    "www.planningportal.nsw.gov.au",
    "suno.com",
  ],
} as const;
