import { SERVICE_ENDPOINTS } from "@/utils/config/serviceEndpoints";

export const ARCGIS_SALES_ENDPOINT = SERVICE_ENDPOINTS.PROPERTY_SALES;
export const ARCGIS_BOUNDARY_ENDPOINT = SERVICE_ENDPOINTS.PROPERTY;
export const ARCGIS_FLOOD_ENDPOINT = SERVICE_ENDPOINTS.FLOOD_EXTENTS;
export const ARCGIS_BUSHFIRE_ENDPOINT = SERVICE_ENDPOINTS.BUSHFIRE;
export const ARCGIS_BIODIVERSITY_ENDPOINT = SERVICE_ENDPOINTS.BIODIVERSITY_VALUES;
export const ARCGIS_HERITAGE_ENDPOINT = SERVICE_ENDPOINTS.HERITAGE;
export const ARCGIS_CONTAMINATION_ENDPOINT = `${SERVICE_ENDPOINTS.CONTAMINATION}/0`;
export const ARCGIS_AIRCRAFT_NOISE_RANDWICK_ENDPOINT = SERVICE_ENDPOINTS.AIRCRAFT_NOISE_RANDWICK;
export const ARCGIS_AIRCRAFT_NOISE_NSW_ENDPOINT = SERVICE_ENDPOINTS.AIRCRAFT_NOISE_NSW;
export const PLANNING_PORTAL_ENDPOINT = SERVICE_ENDPOINTS.PLANNING_PORTAL;

/** NSW Planning Portal map service layer indices for intersect queries. */
export const PLANNING_LAYER_IDS = {
  FSR: 11,
  HOB: 14,
  ZONE: 19,
  LAND_RESERVATION_ACQUISITION: 24,
} as const;

export const SALES_LAYER_INDICES = [1, 2, 3] as const;

export const REQUEST_TIMEOUT = 10000; // 10 seconds
